# See: https://prettier.io/docs/en/configuration

printWidth: 80
tabWidth: 2
useTabs: false
semi: true
singleQuote: false
quoteProps: as-needed
trailingComma: all
bracketSpacing: true
bracketSameLine: true
arrowParens: always
proseWrap: always
endOfLine: lf
